# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 626f9c5ddc592360da127949e2187278236ad96ba673304d6dc4843d3183dacfc7a3833dfdfd24e6218e2ff63f35df151ae76cf1e0d8e9cf000dce89196f9415

test:
  secret_key_base: 71ca7b6ba9bf4a27e581982cafa095270938ea65f49f4c7af0494713e7a3646cc25d229e95a3355b639f600822d4d1acb38fdc2583371b226fede1f43ff4911f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
